### ISSUE TITLE
Unable to apply CustomPodAutoscaler

### ISSUE THREAD

**Issue by harinarayanan-muthukumar** [jthomperoo/custom-pod-autoscaler-operator#100]
I was able to install the CustomPodAutoscaler operator via helm (cluster wide) on our AKS Cluster and the pod started without any issues . But when I try to install an CustomPodAutoscaler via the below YAML it throws me an error saying resource mapping not found for name. 

```
error: resource mapping not found for name: "telegraf-operator" namespace: "" from ".\\Custom HPA.yml": no matches for kind "CustomPodAutoscaler" in version "custompodautoscaler.com/v1alpha1"
ensure CRDs are installed first
```

Below is the YAML I used  :

```
apiVersion: custompodautoscaler.com/v1alpha1
kind: CustomPodAutoscaler
metadata:
  name: telegraf-operator
spec:
  template:
    spec:
      containers:
      - name: horizontal-pod-autoscaler-example
        image: horizontal-pod-autoscaler:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telegraf-operator
  config: 
    - name: minReplicas
      value: "2"
    - name: maxReplicas
      value: "5"
    - name: interval
      value: "30000"
    - name: tolerance
      value: "0.2"
    - name: downscaleStabilization
      value: "120"
    - name: metrics
      value: |
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
---
```

The reference deployment does exist on the namespace and all that was verified . Unsure if I am missing some thing here and need help figuring this out.
