### ISSUE TITLE
Use scaleTargetRef rather than selector

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/custom-pod-autoscaler-operator#33]
Use `scaleTargetRef` rather than `selector`, better consistency with Horizontal Pod Autoscaler.
```yaml
apiVersion: custompodautoscaler.com/v1alpha1
kind: CustomPodAutoscaler
metadata:
  name: player-count-scaler
spec:
  image: example-python-custom-pod-autoscaler:latest
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-metric
```
