### ISSUE TITLE
roleRequiresMetricsServer flag does not generate role that works for custom or external metrics

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/custom-pod-autoscaler-operator#79]
**Describe the bug**
The `roleRequiresMetricsServer` flag does not generate a role that works for custom or external metrics - it only
has permission to access the `metrics.k8s.io` group, but needs permission to access `custom.metrics.k8s.io` and `external.metrics.k8s.io` also.

**To Reproduce**
1. Deploy the CPAO.
2. Install a CPA that queries custom metrics and uses the `roleRequiresMetricsServer` flag to generate a role.
3. The CPA will fail with this error:

```txt
invalid metrics (1 invalid out of 1), first error is: failed to get pods metric: unable to get metric my_custom_metric: unable to fetch metrics from custom metrics API: pods.custom.metrics.k8s.io "*" is forbidden: User "system:serviceaccount:default:my-cpa" cannot get resource "pods/my_custom_metric" in API group "custom.metrics.k8s.io" in the namespace "default"
```

**Expected behavior**
The role created should have access to K8s custom and external metrics.

**Kubernetes Details (`kubectl version`):**
All K8s versions.

**Custom Pod Autoscaler Operator Details:**
`v1.1.0`

**Additional context**
The fix here is to create a role with the correct permissions.

**Workaround**
Just include the `provisionRole: false` flag in your CPA definition, and create a custom role that is like this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <NAME OF YOUR CUSTOM POD AUTOSCALER>
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
  ```
