### ISSUE TITLE
Changing Pod name through metadata can cause 2 pods to be created

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/custom-pod-autoscaler-operator#95]
**Describe the bug**
Change introduced in #93 means that you can modify the pod name independently of the CPA name, this causes issues because you can change the name of the pod, so the old pod won't get any reconcile event, meaning it wont be deleted and you will end up with two pods.

**To Reproduce**
1. Deploy a CPA with some metadata for the Pod name:

```yaml
spec:
  template:
    metadata:
      name: test-pod
...
```

2. Wait and see the Pod is created.
3. Update the metadata to change the Pod name:

```yaml
spec:
  template:
    metadata:
      name: test-pod-2
...
```

4. Wait and see that there are now 2 pods.

**Expected behavior**
The old pod should be deleted as the new one is created.

**Kubernetes Details (`kubectl version`):**

```
v1.22.7
```

**Custom Pod Autoscaler Operator Details:**
Unreleased CPA based off `master` (commit [`1efee1a5076b20aaccb467b39314fcc2fae68ec4`](https://github.com/jthomperoo/custom-pod-autoscaler-operator/commit/1efee1a5076b20aaccb467b39314fcc2fae68ec4))

**Additional context**
N/A
